image: mattkingastec/hls_env:latest

stages:
- list_tools
- check_server

list_tools:
  stage: list_tools
  script: "which python3"

check_server:
  stage: check_server
  script:
  - cd ~/test_scripts
  - python3 zeromq_test.py

