# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'astra_comparison_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1233, 639)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.main_tab_widget = QtGui.QTabWidget(self.centralwidget)
        self.main_tab_widget.setEnabled(True)
        self.main_tab_widget.setTabShape(QtGui.QTabWidget.Rounded)
        self.main_tab_widget.setObjectName(_fromUtf8("main_tab_widget"))
        self.scan_tab = QtGui.QWidget()
        self.scan_tab.setObjectName(_fromUtf8("scan_tab"))
        self.layoutWidget = QtGui.QWidget(self.scan_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 450))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.non_magnet_arguments_layout = QtGui.QGridLayout(self.layoutWidget)
        self.non_magnet_arguments_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.non_magnet_arguments_layout.setObjectName(_fromUtf8("non_magnet_arguments_layout"))
        self.linac_1_parameter_form_layout = QtGui.QFormLayout()
        self.linac_1_parameter_form_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.linac_1_parameter_form_layout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.linac_1_parameter_form_layout.setHorizontalSpacing(3)
        self.linac_1_parameter_form_layout.setVerticalSpacing(30)
        self.linac_1_parameter_form_layout.setObjectName(_fromUtf8("linac_1_parameter_form_layout"))
        self.linac_1_gradient_line = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac_1_gradient_line.sizePolicy().hasHeightForWidth())
        self.linac_1_gradient_line.setSizePolicy(sizePolicy)
        self.linac_1_gradient_line.setMinimumSize(QtCore.QSize(74, 22))
        self.linac_1_gradient_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac_1_gradient_line.setObjectName(_fromUtf8("linac_1_gradient_line"))
        self.linac_1_parameter_form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.linac_1_gradient_line)
        self.linac1_phase_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_phase_label.sizePolicy().hasHeightForWidth())
        self.linac1_phase_label.setSizePolicy(sizePolicy)
        self.linac1_phase_label.setObjectName(_fromUtf8("linac1_phase_label"))
        self.linac_1_parameter_form_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.linac1_phase_label)
        self.linac1_phase_line = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_phase_line.sizePolicy().hasHeightForWidth())
        self.linac1_phase_line.setSizePolicy(sizePolicy)
        self.linac1_phase_line.setMinimumSize(QtCore.QSize(74, 22))
        self.linac1_phase_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_phase_line.setObjectName(_fromUtf8("linac1_phase_line"))
        self.linac_1_parameter_form_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.linac1_phase_line)
        self.bucking_coil_and_sol_strength_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bucking_coil_and_sol_strength_label.sizePolicy().hasHeightForWidth())
        self.bucking_coil_and_sol_strength_label.setSizePolicy(sizePolicy)
        self.bucking_coil_and_sol_strength_label.setObjectName(_fromUtf8("bucking_coil_and_sol_strength_label"))
        self.linac_1_parameter_form_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.bucking_coil_and_sol_strength_label)
        self.bucking_coil_and_sol_strength = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bucking_coil_and_sol_strength.sizePolicy().hasHeightForWidth())
        self.bucking_coil_and_sol_strength.setSizePolicy(sizePolicy)
        self.bucking_coil_and_sol_strength.setMinimumSize(QtCore.QSize(74, 22))
        self.bucking_coil_and_sol_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.bucking_coil_and_sol_strength.setObjectName(_fromUtf8("bucking_coil_and_sol_strength"))
        self.linac_1_parameter_form_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.bucking_coil_and_sol_strength)
        self.linac1_sol1_strength_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_sol1_strength_label.sizePolicy().hasHeightForWidth())
        self.linac1_sol1_strength_label.setSizePolicy(sizePolicy)
        self.linac1_sol1_strength_label.setObjectName(_fromUtf8("linac1_sol1_strength_label"))
        self.linac_1_parameter_form_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.linac1_sol1_strength_label)
        self.linac1_sol1_strength = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_sol1_strength.sizePolicy().hasHeightForWidth())
        self.linac1_sol1_strength.setSizePolicy(sizePolicy)
        self.linac1_sol1_strength.setMinimumSize(QtCore.QSize(74, 22))
        self.linac1_sol1_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_sol1_strength.setObjectName(_fromUtf8("linac1_sol1_strength"))
        self.linac_1_parameter_form_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.linac1_sol1_strength)
        self.linac1_sol2_strength_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_sol2_strength_label.sizePolicy().hasHeightForWidth())
        self.linac1_sol2_strength_label.setSizePolicy(sizePolicy)
        self.linac1_sol2_strength_label.setObjectName(_fromUtf8("linac1_sol2_strength_label"))
        self.linac_1_parameter_form_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.linac1_sol2_strength_label)
        self.linac1_sol2_strength = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_sol2_strength.sizePolicy().hasHeightForWidth())
        self.linac1_sol2_strength.setSizePolicy(sizePolicy)
        self.linac1_sol2_strength.setMinimumSize(QtCore.QSize(74, 22))
        self.linac1_sol2_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_sol2_strength.setObjectName(_fromUtf8("linac1_sol2_strength"))
        self.linac_1_parameter_form_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.linac1_sol2_strength)
        self.end_of_line_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_of_line_label.sizePolicy().hasHeightForWidth())
        self.end_of_line_label.setSizePolicy(sizePolicy)
        self.end_of_line_label.setObjectName(_fromUtf8("end_of_line_label"))
        self.linac_1_parameter_form_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.end_of_line_label)
        self.end_of_line = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_of_line.sizePolicy().hasHeightForWidth())
        self.end_of_line.setSizePolicy(sizePolicy)
        self.end_of_line.setMinimumSize(QtCore.QSize(74, 22))
        self.end_of_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.end_of_line.setObjectName(_fromUtf8("end_of_line"))
        self.linac_1_parameter_form_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.end_of_line)
        self.injector_space_charge_switch_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.injector_space_charge_switch_label.sizePolicy().hasHeightForWidth())
        self.injector_space_charge_switch_label.setSizePolicy(sizePolicy)
        self.injector_space_charge_switch_label.setObjectName(_fromUtf8("injector_space_charge_switch_label"))
        self.linac_1_parameter_form_layout.setWidget(6, QtGui.QFormLayout.LabelRole, self.injector_space_charge_switch_label)
        self.injector_space_charge = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.injector_space_charge.sizePolicy().hasHeightForWidth())
        self.injector_space_charge.setSizePolicy(sizePolicy)
        self.injector_space_charge.setText(_fromUtf8(""))
        self.injector_space_charge.setChecked(True)
        self.injector_space_charge.setObjectName(_fromUtf8("injector_space_charge"))
        self.linac_1_parameter_form_layout.setWidget(6, QtGui.QFormLayout.FieldRole, self.injector_space_charge)
        self.rest_of_line_space_charge_switch_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest_of_line_space_charge_switch_label.sizePolicy().hasHeightForWidth())
        self.rest_of_line_space_charge_switch_label.setSizePolicy(sizePolicy)
        self.rest_of_line_space_charge_switch_label.setObjectName(_fromUtf8("rest_of_line_space_charge_switch_label"))
        self.linac_1_parameter_form_layout.setWidget(7, QtGui.QFormLayout.LabelRole, self.rest_of_line_space_charge_switch_label)
        self.rest_of_line_space_charge = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest_of_line_space_charge.sizePolicy().hasHeightForWidth())
        self.rest_of_line_space_charge.setSizePolicy(sizePolicy)
        self.rest_of_line_space_charge.setText(_fromUtf8(""))
        self.rest_of_line_space_charge.setChecked(True)
        self.rest_of_line_space_charge.setObjectName(_fromUtf8("rest_of_line_space_charge"))
        self.linac_1_parameter_form_layout.setWidget(7, QtGui.QFormLayout.FieldRole, self.rest_of_line_space_charge)
        self.linac1_gradient_label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1_gradient_label.sizePolicy().hasHeightForWidth())
        self.linac1_gradient_label.setSizePolicy(sizePolicy)
        self.linac1_gradient_label.setObjectName(_fromUtf8("linac1_gradient_label"))
        self.linac_1_parameter_form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.linac1_gradient_label)
        self.non_magnet_arguments_layout.addLayout(self.linac_1_parameter_form_layout, 0, 1, 1, 1)
        self.gun_parameter_form_layout = QtGui.QFormLayout()
        self.gun_parameter_form_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gun_parameter_form_layout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.gun_parameter_form_layout.setHorizontalSpacing(5)
        self.gun_parameter_form_layout.setVerticalSpacing(25)
        self.gun_parameter_form_layout.setObjectName(_fromUtf8("gun_parameter_form_layout"))
        self.macro_particle_label = QtGui.QLabel(self.layoutWidget)
        self.macro_particle_label.setObjectName(_fromUtf8("macro_particle_label"))
        self.gun_parameter_form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.macro_particle_label)
        self.macro_particle = QtGui.QLineEdit(self.layoutWidget)
        self.macro_particle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.macro_particle.setObjectName(_fromUtf8("macro_particle"))
        self.gun_parameter_form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.macro_particle)
        self.laser_pulse_length_label = QtGui.QLabel(self.layoutWidget)
        self.laser_pulse_length_label.setObjectName(_fromUtf8("laser_pulse_length_label"))
        self.gun_parameter_form_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.laser_pulse_length_label)
        self.laser_pulse_length = QtGui.QLineEdit(self.layoutWidget)
        self.laser_pulse_length.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.laser_pulse_length.setObjectName(_fromUtf8("laser_pulse_length"))
        self.gun_parameter_form_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.laser_pulse_length)
        self.spot_size_label = QtGui.QLabel(self.layoutWidget)
        self.spot_size_label.setObjectName(_fromUtf8("spot_size_label"))
        self.gun_parameter_form_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.spot_size_label)
        self.spot_size_line = QtGui.QLineEdit(self.layoutWidget)
        self.spot_size_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.spot_size_line.setObjectName(_fromUtf8("spot_size_line"))
        self.gun_parameter_form_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spot_size_line)
        self.charge_label = QtGui.QLabel(self.layoutWidget)
        self.charge_label.setObjectName(_fromUtf8("charge_label"))
        self.gun_parameter_form_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.charge_label)
        self.charge = QtGui.QLineEdit(self.layoutWidget)
        self.charge.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.charge.setObjectName(_fromUtf8("charge"))
        self.gun_parameter_form_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.charge)
        self.gun_gradient_label = QtGui.QLabel(self.layoutWidget)
        self.gun_gradient_label.setObjectName(_fromUtf8("gun_gradient_label"))
        self.gun_parameter_form_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.gun_gradient_label)
        self.gun_gradient = QtGui.QLineEdit(self.layoutWidget)
        self.gun_gradient.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.gun_gradient.setObjectName(_fromUtf8("gun_gradient"))
        self.gun_parameter_form_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.gun_gradient)
        self.gun_phase_label = QtGui.QLabel(self.layoutWidget)
        self.gun_phase_label.setObjectName(_fromUtf8("gun_phase_label"))
        self.gun_parameter_form_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.gun_phase_label)
        self.gun_phase = QtGui.QLineEdit(self.layoutWidget)
        self.gun_phase.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.gun_phase.setObjectName(_fromUtf8("gun_phase"))
        self.gun_parameter_form_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.gun_phase)
        self.non_magnet_arguments_layout.addLayout(self.gun_parameter_form_layout, 0, 0, 1, 1)
        self.layoutWidget_2 = QtGui.QWidget(self.scan_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(604, 10, 591, 451))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.magnet_quad_strength_layout = QtGui.QGridLayout(self.layoutWidget_2)
        self.magnet_quad_strength_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.magnet_quad_strength_layout.setObjectName(_fromUtf8("magnet_quad_strength_layout"))
        self.ba1_label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ba1_label.setFont(font)
        self.ba1_label.setObjectName(_fromUtf8("ba1_label"))
        self.magnet_quad_strength_layout.addWidget(self.ba1_label, 2, 1, 1, 1)
        self.c2v_label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.c2v_label.setFont(font)
        self.c2v_label.setObjectName(_fromUtf8("c2v_label"))
        self.magnet_quad_strength_layout.addWidget(self.c2v_label, 2, 0, 1, 1)
        self.vela_quads_layout = QtGui.QFormLayout()
        self.vela_quads_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.vela_quads_layout.setObjectName(_fromUtf8("vela_quads_layout"))
        self.vela_quad1_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad1_strength_label.setObjectName(_fromUtf8("vela_quad1_strength_label"))
        self.vela_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.vela_quad1_strength_label)
        self.vela_quad2_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad2_strength_label.setObjectName(_fromUtf8("vela_quad2_strength_label"))
        self.vela_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.vela_quad2_strength_label)
        self.vela_quad2_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad2_strength.setObjectName(_fromUtf8("vela_quad2_strength"))
        self.vela_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vela_quad2_strength)
        self.vela_quad3_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad3_strength_label.setObjectName(_fromUtf8("vela_quad3_strength_label"))
        self.vela_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.vela_quad3_strength_label)
        self.vela_quad3_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad3_strength.setObjectName(_fromUtf8("vela_quad3_strength"))
        self.vela_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.vela_quad3_strength)
        self.vela_quad4_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad4_strength_label.setObjectName(_fromUtf8("vela_quad4_strength_label"))
        self.vela_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.vela_quad4_strength_label)
        self.vela_quad4_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad4_strength.setObjectName(_fromUtf8("vela_quad4_strength"))
        self.vela_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.vela_quad4_strength)
        self.vela_quad5_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad5_strength_label.setObjectName(_fromUtf8("vela_quad5_strength_label"))
        self.vela_quads_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.vela_quad5_strength_label)
        self.vela_quad5_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad5_strength.setObjectName(_fromUtf8("vela_quad5_strength"))
        self.vela_quads_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.vela_quad5_strength)
        self.vela_quad6_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.vela_quad6_strength_label.setObjectName(_fromUtf8("vela_quad6_strength_label"))
        self.vela_quads_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.vela_quad6_strength_label)
        self.vela_quad6_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad6_strength.setObjectName(_fromUtf8("vela_quad6_strength"))
        self.vela_quads_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.vela_quad6_strength)
        self.vela_quad1_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.vela_quad1_strength.setObjectName(_fromUtf8("vela_quad1_strength"))
        self.vela_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.vela_quad1_strength)
        self.magnet_quad_strength_layout.addLayout(self.vela_quads_layout, 1, 1, 1, 1)
        self.c2v_quads_layout = QtGui.QFormLayout()
        self.c2v_quads_layout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.c2v_quads_layout.setObjectName(_fromUtf8("c2v_quads_layout"))
        self.c2v_quad1_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.c2v_quad1_strength.setObjectName(_fromUtf8("c2v_quad1_strength"))
        self.c2v_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.c2v_quad1_strength)
        self.c2v_quad2_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.c2v_quad2_strength_label.setObjectName(_fromUtf8("c2v_quad2_strength_label"))
        self.c2v_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.c2v_quad2_strength_label)
        self.c2v_quad2_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.c2v_quad2_strength.setObjectName(_fromUtf8("c2v_quad2_strength"))
        self.c2v_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.c2v_quad2_strength)
        self.c2v_quad3_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.c2v_quad3_strength_label.setObjectName(_fromUtf8("c2v_quad3_strength_label"))
        self.c2v_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.c2v_quad3_strength_label)
        self.c2v_quad3_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.c2v_quad3_strength.setObjectName(_fromUtf8("c2v_quad3_strength"))
        self.c2v_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.c2v_quad3_strength)
        self.c2v_quad1_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.c2v_quad1_strength_label.setObjectName(_fromUtf8("c2v_quad1_strength_label"))
        self.c2v_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.c2v_quad1_strength_label)
        self.magnet_quad_strength_layout.addLayout(self.c2v_quads_layout, 3, 0, 1, 1)
        self.s02_label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.s02_label.setFont(font)
        self.s02_label.setObjectName(_fromUtf8("s02_label"))
        self.magnet_quad_strength_layout.addWidget(self.s02_label, 0, 0, 1, 1)
        self.ba1_quads_layout = QtGui.QFormLayout()
        self.ba1_quads_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ba1_quads_layout.setObjectName(_fromUtf8("ba1_quads_layout"))
        self.ba1_quad1_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad1_strength_label.setObjectName(_fromUtf8("ba1_quad1_strength_label"))
        self.ba1_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ba1_quad1_strength_label)
        self.ba1_quad1_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad1_strength.setObjectName(_fromUtf8("ba1_quad1_strength"))
        self.ba1_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ba1_quad1_strength)
        self.ba1_quad2_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad2_strength_label.setObjectName(_fromUtf8("ba1_quad2_strength_label"))
        self.ba1_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ba1_quad2_strength_label)
        self.ba1_quad2_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad2_strength.setObjectName(_fromUtf8("ba1_quad2_strength"))
        self.ba1_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ba1_quad2_strength)
        self.ba1_quad3_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad3_strength_label.setObjectName(_fromUtf8("ba1_quad3_strength_label"))
        self.ba1_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ba1_quad3_strength_label)
        self.ba1_quad3_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad3_strength.setObjectName(_fromUtf8("ba1_quad3_strength"))
        self.ba1_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ba1_quad3_strength)
        self.ba1_quad4_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad4_strength_label.setObjectName(_fromUtf8("ba1_quad4_strength_label"))
        self.ba1_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.ba1_quad4_strength_label)
        self.ba1_quad4_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad4_strength.setObjectName(_fromUtf8("ba1_quad4_strength"))
        self.ba1_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ba1_quad4_strength)
        self.ba1_quad5_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad5_strength_label.setObjectName(_fromUtf8("ba1_quad5_strength_label"))
        self.ba1_quads_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.ba1_quad5_strength_label)
        self.ba1_quad5_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad5_strength.setObjectName(_fromUtf8("ba1_quad5_strength"))
        self.ba1_quads_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ba1_quad5_strength)
        self.ba1_quad6_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad6_strength_label.setObjectName(_fromUtf8("ba1_quad6_strength_label"))
        self.ba1_quads_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.ba1_quad6_strength_label)
        self.ba1_quad6_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad6_strength.setObjectName(_fromUtf8("ba1_quad6_strength"))
        self.ba1_quads_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ba1_quad6_strength)
        self.ba1_quad7_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.ba1_quad7_strength_label.setObjectName(_fromUtf8("ba1_quad7_strength_label"))
        self.ba1_quads_layout.setWidget(6, QtGui.QFormLayout.LabelRole, self.ba1_quad7_strength_label)
        self.ba1_quad7_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.ba1_quad7_strength.setObjectName(_fromUtf8("ba1_quad7_strength"))
        self.ba1_quads_layout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ba1_quad7_strength)
        self.magnet_quad_strength_layout.addLayout(self.ba1_quads_layout, 3, 1, 1, 1)
        self.s02_quads_layout = QtGui.QFormLayout()
        self.s02_quads_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.s02_quads_layout.setObjectName(_fromUtf8("s02_quads_layout"))
        self.s02_quad1_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.s02_quad1_strength_label.setObjectName(_fromUtf8("s02_quad1_strength_label"))
        self.s02_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.s02_quad1_strength_label)
        self.s02_quad1_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.s02_quad1_strength.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.s02_quad1_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad1_strength.setObjectName(_fromUtf8("s02_quad1_strength"))
        self.s02_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.s02_quad1_strength)
        self.s02_quad2_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.s02_quad2_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad2_strength.setObjectName(_fromUtf8("s02_quad2_strength"))
        self.s02_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.s02_quad2_strength)
        self.s02_quad3_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.s02_quad3_strength_label.setObjectName(_fromUtf8("s02_quad3_strength_label"))
        self.s02_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.s02_quad3_strength_label)
        self.s02_quad3_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.s02_quad3_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad3_strength.setObjectName(_fromUtf8("s02_quad3_strength"))
        self.s02_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.s02_quad3_strength)
        self.s02_quad4_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.s02_quad4_strength_label.setObjectName(_fromUtf8("s02_quad4_strength_label"))
        self.s02_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.s02_quad4_strength_label)
        self.s02_quad4_strength = QtGui.QLineEdit(self.layoutWidget_2)
        self.s02_quad4_strength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad4_strength.setObjectName(_fromUtf8("s02_quad4_strength"))
        self.s02_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.s02_quad4_strength)
        self.s02_quad2_strength_label = QtGui.QLabel(self.layoutWidget_2)
        self.s02_quad2_strength_label.setObjectName(_fromUtf8("s02_quad2_strength_label"))
        self.s02_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.s02_quad2_strength_label)
        self.magnet_quad_strength_layout.addLayout(self.s02_quads_layout, 1, 0, 1, 1)
        self.vela_label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.vela_label.setFont(font)
        self.vela_label.setObjectName(_fromUtf8("vela_label"))
        self.magnet_quad_strength_layout.addWidget(self.vela_label, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.scan_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 460, 581, 81))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.parameter_scan_layout = QtGui.QGridLayout(self.layoutWidget1)
        self.parameter_scan_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.parameter_scan_layout.setObjectName(_fromUtf8("parameter_scan_layout"))
        self.parameter_scan_to_value_label = QtGui.QLabel(self.layoutWidget1)
        self.parameter_scan_to_value_label.setObjectName(_fromUtf8("parameter_scan_to_value_label"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_to_value_label, 2, 2, 1, 1)
        self.parameter_scan_label = QtGui.QLabel(self.layoutWidget1)
        self.parameter_scan_label.setObjectName(_fromUtf8("parameter_scan_label"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_label, 1, 0, 1, 1)
        self.parameter_scan_to_value = QtGui.QLineEdit(self.layoutWidget1)
        self.parameter_scan_to_value.setObjectName(_fromUtf8("parameter_scan_to_value"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_to_value, 2, 3, 1, 1)
        self.parameter_scan_step_size_label = QtGui.QLabel(self.layoutWidget1)
        self.parameter_scan_step_size_label.setObjectName(_fromUtf8("parameter_scan_step_size_label"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_step_size_label, 2, 4, 1, 1)
        self.parameter_scan_from_value_label = QtGui.QLabel(self.layoutWidget1)
        self.parameter_scan_from_value_label.setObjectName(_fromUtf8("parameter_scan_from_value_label"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_from_value_label, 2, 0, 1, 1)
        self.parameter_scan_from_value = QtGui.QLineEdit(self.layoutWidget1)
        self.parameter_scan_from_value.setObjectName(_fromUtf8("parameter_scan_from_value"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_from_value, 2, 1, 1, 1)
        self.parameter_scan_step_size = QtGui.QLineEdit(self.layoutWidget1)
        self.parameter_scan_step_size.setObjectName(_fromUtf8("parameter_scan_step_size"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_step_size, 2, 5, 1, 1)
        self.parameter = QtGui.QComboBox(self.layoutWidget1)
        self.parameter.setObjectName(_fromUtf8("parameter"))
        self.parameter_scan_layout.addWidget(self.parameter, 1, 1, 1, 5)
        self.parameter_scan = QtGui.QCheckBox(self.layoutWidget1)
        self.parameter_scan.setText(_fromUtf8(""))
        self.parameter_scan.setObjectName(_fromUtf8("parameter_scan"))
        self.parameter_scan_layout.addWidget(self.parameter_scan, 0, 3, 1, 1)
        self.parameter_scan_section_label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.parameter_scan_section_label.setFont(font)
        self.parameter_scan_section_label.setObjectName(_fromUtf8("parameter_scan_section_label"))
        self.parameter_scan_layout.addWidget(self.parameter_scan_section_label, 0, 0, 1, 3)
        self.layoutWidget2 = QtGui.QWidget(self.scan_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(600, 460, 601, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.directory_and_run_button_grid_layout = QtGui.QGridLayout(self.layoutWidget2)
        self.directory_and_run_button_grid_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.directory_and_run_button_grid_layout.setObjectName(_fromUtf8("directory_and_run_button_grid_layout"))
        self.directory_form_layout = QtGui.QFormLayout()
        self.directory_form_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.directory_form_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.directory_form_layout.setObjectName(_fromUtf8("directory_form_layout"))
        self.directory_label = QtGui.QLabel(self.layoutWidget2)
        self.directory_label.setObjectName(_fromUtf8("directory_label"))
        self.directory_form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.directory_label)
        self.directory = QtGui.QLineEdit(self.layoutWidget2)
        self.directory.setObjectName(_fromUtf8("directory"))
        self.directory_form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.directory)
        self.directory_and_run_button_grid_layout.addLayout(self.directory_form_layout, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.layoutWidget2)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.directory_and_run_button_grid_layout.addWidget(self.runButton, 0, 1, 1, 1)
        self.main_tab_widget.addTab(self.scan_tab, _fromUtf8(""))
        self.post_tab = QtGui.QWidget()
        self.post_tab.setObjectName(_fromUtf8("post_tab"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.post_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 1181, 41))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.directory_post_layout = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.directory_post_layout.setObjectName(_fromUtf8("directory_post_layout"))
        self.directory_post_label = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.directory_post_label.setObjectName(_fromUtf8("directory_post_label"))
        self.directory_post_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.directory_post_label)
        self.directory_post_line_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.directory_post_line_edit.setObjectName(_fromUtf8("directory_post_line_edit"))
        self.directory_post_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.directory_post_line_edit)
        self.gridLayoutWidget = QtGui.QWidget(self.post_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 110, 1181, 311))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.graphics_post_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.graphics_post_layout.setObjectName(_fromUtf8("graphics_post_layout"))
        self.graphics_post_graphics_view_1 = QtGui.QGraphicsView(self.gridLayoutWidget)
        self.graphics_post_graphics_view_1.setObjectName(_fromUtf8("graphics_post_graphics_view_1"))
        self.graphics_post_layout.addWidget(self.graphics_post_graphics_view_1, 0, 1, 1, 1)
        self.graphics_post_graphics_view_2 = QtGui.QGraphicsView(self.gridLayoutWidget)
        self.graphics_post_graphics_view_2.setObjectName(_fromUtf8("graphics_post_graphics_view_2"))
        self.graphics_post_layout.addWidget(self.graphics_post_graphics_view_2, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.post_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1181, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.options_post_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.options_post_layout.setObjectName(_fromUtf8("options_post_layout"))
        self.options_post_runs_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.options_post_runs_label.setFont(font)
        self.options_post_runs_label.setObjectName(_fromUtf8("options_post_runs_label"))
        self.options_post_layout.addWidget(self.options_post_runs_label)
        self.directory_post_combo_box = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.directory_post_combo_box.setObjectName(_fromUtf8("directory_post_combo_box"))
        self.options_post_layout.addWidget(self.directory_post_combo_box)
        self.directory_post_combo_box_2 = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.directory_post_combo_box_2.setObjectName(_fromUtf8("directory_post_combo_box_2"))
        self.options_post_layout.addWidget(self.directory_post_combo_box_2)
        self.options_post_plot_label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.options_post_plot_label.setFont(font)
        self.options_post_plot_label.setObjectName(_fromUtf8("options_post_plot_label"))
        self.options_post_layout.addWidget(self.options_post_plot_label)
        self.directory_post_combo_box_4 = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.directory_post_combo_box_4.setObjectName(_fromUtf8("directory_post_combo_box_4"))
        self.options_post_layout.addWidget(self.directory_post_combo_box_4)
        self.directory_post_combo_box_3 = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.directory_post_combo_box_3.setObjectName(_fromUtf8("directory_post_combo_box_3"))
        self.options_post_layout.addWidget(self.directory_post_combo_box_3)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.post_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 420, 1181, 41))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.runButton_post_layout = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.runButton_post_layout.setObjectName(_fromUtf8("runButton_post_layout"))
        self.runButton_post = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.runButton_post.setMinimumSize(QtCore.QSize(180, 30))
        self.runButton_post.setObjectName(_fromUtf8("runButton_post"))
        self.runButton_post_layout.addWidget(self.runButton_post, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.runButton_post_layout.addItem(spacerItem, 0, 0, 1, 1)
        self.main_tab_widget.addTab(self.post_tab, _fromUtf8(""))
        self.distribution_tab = QtGui.QWidget()
        self.distribution_tab.setObjectName(_fromUtf8("distribution_tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.distribution_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 1181, 291))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.graphics_dyn_plot_layout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.graphics_dyn_plot_layout.setObjectName(_fromUtf8("graphics_dyn_plot_layout"))
        self.graphics_post_dyn_plot_widget = PlotWidget(self.gridLayoutWidget_2)
        self.graphics_post_dyn_plot_widget.setObjectName(_fromUtf8("graphics_post_dyn_plot_widget"))
        self.graphics_dyn_plot_layout.addWidget(self.graphics_post_dyn_plot_widget, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.distribution_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, -3, 1181, 61))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.variables_dyn_plot_layout = QtGui.QGridLayout(self.horizontalLayoutWidget_2)
        self.variables_dyn_plot_layout.setObjectName(_fromUtf8("variables_dyn_plot_layout"))
        self.variables_dyn_plot_combo_box_1 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.variables_dyn_plot_combo_box_1.setObjectName(_fromUtf8("variables_dyn_plot_combo_box_1"))
        self.variables_dyn_plot_layout.addWidget(self.variables_dyn_plot_combo_box_1, 1, 1, 1, 1)
        self.variables_dyn_plot_combo_box_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.variables_dyn_plot_combo_box_2.setObjectName(_fromUtf8("variables_dyn_plot_combo_box_2"))
        self.variables_dyn_plot_layout.addWidget(self.variables_dyn_plot_combo_box_2, 1, 2, 1, 1)
        self.directory_dyn_plot_line_edit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.directory_dyn_plot_line_edit.setObjectName(_fromUtf8("directory_dyn_plot_line_edit"))
        self.variables_dyn_plot_layout.addWidget(self.directory_dyn_plot_line_edit, 0, 2, 1, 1)
        self.directory_dyn_plot_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.directory_dyn_plot_label.setFont(font)
        self.directory_dyn_plot_label.setObjectName(_fromUtf8("directory_dyn_plot_label"))
        self.variables_dyn_plot_layout.addWidget(self.directory_dyn_plot_label, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.variables_dyn_plot_layout.addItem(spacerItem1, 0, 1, 1, 1)
        self.variables_dyn_plot_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.variables_dyn_plot_label.setFont(font)
        self.variables_dyn_plot_label.setObjectName(_fromUtf8("variables_dyn_plot_label"))
        self.variables_dyn_plot_layout.addWidget(self.variables_dyn_plot_label, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(self.distribution_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(859, 380, 331, 80))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.dyn_plot_run_button_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.dyn_plot_run_button_layout.setObjectName(_fromUtf8("dyn_plot_run_button_layout"))
        self.runButton_dyn_plot = QtGui.QPushButton(self.verticalLayoutWidget)
        self.runButton_dyn_plot.setObjectName(_fromUtf8("runButton_dyn_plot"))
        self.dyn_plot_run_button_layout.addWidget(self.runButton_dyn_plot)
        self.dyn_plot_progressBar = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.dyn_plot_progressBar.setProperty("value", 0)
        self.dyn_plot_progressBar.setObjectName(_fromUtf8("dyn_plot_progressBar"))
        self.dyn_plot_run_button_layout.addWidget(self.dyn_plot_progressBar)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.distribution_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 380, 631, 80))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.dyn_plot_layout = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.dyn_plot_layout.setObjectName(_fromUtf8("dyn_plot_layout"))
        self.save_plot_dyn_plot_check_box = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.save_plot_dyn_plot_check_box.setText(_fromUtf8(""))
        self.save_plot_dyn_plot_check_box.setObjectName(_fromUtf8("save_plot_dyn_plot_check_box"))
        self.dyn_plot_layout.addWidget(self.save_plot_dyn_plot_check_box, 1, 1, 1, 1)
        self.import_dist_dyn_plot_label = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.import_dist_dyn_plot_label.setFont(font)
        self.import_dist_dyn_plot_label.setObjectName(_fromUtf8("import_dist_dyn_plot_label"))
        self.dyn_plot_layout.addWidget(self.import_dist_dyn_plot_label, 0, 0, 1, 1)
        self.save_plot_dyn_plot_label = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.save_plot_dyn_plot_label.setFont(font)
        self.save_plot_dyn_plot_label.setObjectName(_fromUtf8("save_plot_dyn_plot_label"))
        self.dyn_plot_layout.addWidget(self.save_plot_dyn_plot_label, 1, 0, 1, 1)
        self.import_dist_dyn_plot_check_box = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.import_dist_dyn_plot_check_box.setText(_fromUtf8(""))
        self.import_dist_dyn_plot_check_box.setObjectName(_fromUtf8("import_dist_dyn_plot_check_box"))
        self.dyn_plot_layout.addWidget(self.import_dist_dyn_plot_check_box, 0, 1, 1, 1)
        self.output_file_dyn_plot_label = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.output_file_dyn_plot_label.setFont(font)
        self.output_file_dyn_plot_label.setObjectName(_fromUtf8("output_file_dyn_plot_label"))
        self.dyn_plot_layout.addWidget(self.output_file_dyn_plot_label, 2, 0, 1, 1)
        self.output_file_dyn_plot_line_edit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.output_file_dyn_plot_line_edit.setObjectName(_fromUtf8("output_file_dyn_plot_line_edit"))
        self.dyn_plot_layout.addWidget(self.output_file_dyn_plot_line_edit, 2, 1, 1, 1)
        self.main_tab_widget.addTab(self.distribution_tab, _fromUtf8(""))
        self.summary_tab = QtGui.QWidget()
        self.summary_tab.setObjectName(_fromUtf8("summary_tab"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.summary_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 1011, 46))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.summary_title_layout = QtGui.QGridLayout(self.horizontalLayoutWidget_3)
        self.summary_title_layout.setObjectName(_fromUtf8("summary_title_layout"))
        self.summary_title_label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.summary_title_label.setFont(font)
        self.summary_title_label.setObjectName(_fromUtf8("summary_title_label"))
        self.summary_title_layout.addWidget(self.summary_title_label, 0, 0, 1, 1)
        self.directory_summary_line_edit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.directory_summary_line_edit.setObjectName(_fromUtf8("directory_summary_line_edit"))
        self.summary_title_layout.addWidget(self.directory_summary_line_edit, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.summary_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 80, 1181, 311))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.graphics_summary_layout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.graphics_summary_layout.setObjectName(_fromUtf8("graphics_summary_layout"))
        self.summary_graph_plot_widget = PlotWidget(self.gridLayoutWidget_3)
        self.summary_graph_plot_widget.setObjectName(_fromUtf8("summary_graph_plot_widget"))
        self.graphics_summary_layout.addWidget(self.summary_graph_plot_widget, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.summary_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 390, 481, 71))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.summary_options_layout = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.summary_options_layout.setObjectName(_fromUtf8("summary_options_layout"))
        self.summary_save_plot_check_box = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.summary_save_plot_check_box.setText(_fromUtf8(""))
        self.summary_save_plot_check_box.setObjectName(_fromUtf8("summary_save_plot_check_box"))
        self.summary_options_layout.addWidget(self.summary_save_plot_check_box, 0, 1, 1, 1)
        self.summary_save_plot_label = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.summary_save_plot_label.setFont(font)
        self.summary_save_plot_label.setObjectName(_fromUtf8("summary_save_plot_label"))
        self.summary_options_layout.addWidget(self.summary_save_plot_label, 0, 0, 1, 1)
        self.summary_output_file_label = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.summary_output_file_label.setFont(font)
        self.summary_output_file_label.setObjectName(_fromUtf8("summary_output_file_label"))
        self.summary_options_layout.addWidget(self.summary_output_file_label, 1, 0, 1, 1)
        self.summary_output_file_line_edit = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.summary_output_file_line_edit.setObjectName(_fromUtf8("summary_output_file_line_edit"))
        self.summary_options_layout.addWidget(self.summary_output_file_line_edit, 1, 1, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.summary_tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(480, 390, 701, 71))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.runButton_summary_layout = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.runButton_summary_layout.setObjectName(_fromUtf8("runButton_summary_layout"))
        self.runButton_summary = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.runButton_summary.setMinimumSize(QtCore.QSize(160, 35))
        self.runButton_summary.setObjectName(_fromUtf8("runButton_summary"))
        self.runButton_summary_layout.addWidget(self.runButton_summary, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.runButton_summary_layout.addItem(spacerItem2, 0, 0, 1, 1)
        self.main_tab_widget.addTab(self.summary_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.main_tab_widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_YAML = QtGui.QAction(MainWindow)
        self.actionImport_YAML.setObjectName(_fromUtf8("actionImport_YAML"))
        self.actionExport_YAML = QtGui.QAction(MainWindow)
        self.actionExport_YAML.setObjectName(_fromUtf8("actionExport_YAML"))
        self.menuFile.addAction(self.actionImport_YAML)
        self.menuFile.addAction(self.actionExport_YAML)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ASTRA Run Comparison Tool", None))
        self.main_tab_widget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Post-processing</p></body></html>", None))
        self.linac_1_gradient_line.setPlaceholderText(_translate("MainWindow", "21", None))
        self.linac1_phase_label.setText(_translate("MainWindow", "Linac 1 Phase (deg.)", None))
        self.linac1_phase_line.setPlaceholderText(_translate("MainWindow", "-16", None))
        self.bucking_coil_and_sol_strength_label.setText(_translate("MainWindow", "Bucking Coil and Sol Strength (A)", None))
        self.bucking_coil_and_sol_strength.setPlaceholderText(_translate("MainWindow", "0.345", None))
        self.linac1_sol1_strength_label.setText(_translate("MainWindow", "Linac 1 Solenoid 1 Strength (A)", None))
        self.linac1_sol1_strength.setPlaceholderText(_translate("MainWindow", "0.05", None))
        self.linac1_sol2_strength_label.setText(_translate("MainWindow", "Linac 1 Solenoid 2 Strength (A)", None))
        self.linac1_sol2_strength.setPlaceholderText(_translate("MainWindow", "-0.05", None))
        self.end_of_line_label.setText(_translate("MainWindow", "End of Line (cm)", None))
        self.end_of_line.setPlaceholderText(_translate("MainWindow", "337", None))
        self.injector_space_charge_switch_label.setText(_translate("MainWindow", "Injector Space Charge (On/Off)", None))
        self.rest_of_line_space_charge_switch_label.setText(_translate("MainWindow", "Rest of Line Space Charge (On/Off)", None))
        self.linac1_gradient_label.setText(_translate("MainWindow", "Linac 1 Gradient (MV/m)", None))
        self.macro_particle_label.setText(_translate("MainWindow", "No. Macro Particles", None))
        self.macro_particle.setPlaceholderText(_translate("MainWindow", "32", None))
        self.laser_pulse_length_label.setText(_translate("MainWindow", "Laser Pulse Length (ps)", None))
        self.laser_pulse_length.setPlaceholderText(_translate("MainWindow", "3", None))
        self.spot_size_label.setText(_translate("MainWindow", "Spot Size (sig in mm)", None))
        self.spot_size_line.setPlaceholderText(_translate("MainWindow", "0.25", None))
        self.charge_label.setText(_translate("MainWindow", "Charge (nC)", None))
        self.charge.setPlaceholderText(_translate("MainWindow", "0.25", None))
        self.gun_gradient_label.setText(_translate("MainWindow", "Gun Gradient (MV/m)", None))
        self.gun_gradient.setPlaceholderText(_translate("MainWindow", "71.5", None))
        self.gun_phase_label.setText(_translate("MainWindow", "Gun Phase (deg.)", None))
        self.gun_phase.setPlaceholderText(_translate("MainWindow", "-9", None))
        self.ba1_label.setText(_translate("MainWindow", "BA1", None))
        self.c2v_label.setText(_translate("MainWindow", "C2V", None))
        self.vela_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.vela_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.vela_quad2_strength.setPlaceholderText(_translate("MainWindow", "-18.492", None))
        self.vela_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.vela_quad3_strength.setPlaceholderText(_translate("MainWindow", "5.267", None))
        self.vela_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.vela_quad4_strength.setPlaceholderText(_translate("MainWindow", "-5.527", None))
        self.vela_quad5_strength_label.setText(_translate("MainWindow", "QUAD5 Strength (k)", None))
        self.vela_quad5_strength.setPlaceholderText(_translate("MainWindow", "6.721", None))
        self.vela_quad6_strength_label.setText(_translate("MainWindow", "QUAD6 Strength (k)", None))
        self.vela_quad6_strength.setPlaceholderText(_translate("MainWindow", "8.891", None))
        self.vela_quad1_strength.setPlaceholderText(_translate("MainWindow", "20.743", None))
        self.c2v_quad1_strength.setPlaceholderText(_translate("MainWindow", "54.756", None))
        self.c2v_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.c2v_quad2_strength.setPlaceholderText(_translate("MainWindow", "-46.099", None))
        self.c2v_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.c2v_quad3_strength.setPlaceholderText(_translate("MainWindow", "55.974", None))
        self.c2v_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.s02_label.setText(_translate("MainWindow", "S02", None))
        self.ba1_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.ba1_quad1_strength.setPlaceholderText(_translate("MainWindow", "-3.8", None))
        self.ba1_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.ba1_quad2_strength.setPlaceholderText(_translate("MainWindow", "9.9", None))
        self.ba1_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.ba1_quad3_strength.setPlaceholderText(_translate("MainWindow", "-11.5", None))
        self.ba1_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.ba1_quad4_strength.setPlaceholderText(_translate("MainWindow", "5.0", None))
        self.ba1_quad5_strength_label.setText(_translate("MainWindow", "QUAD5 Strength (k)", None))
        self.ba1_quad5_strength.setPlaceholderText(_translate("MainWindow", "-3.5", None))
        self.ba1_quad6_strength_label.setText(_translate("MainWindow", "QUAD6 Strength (k)", None))
        self.ba1_quad6_strength.setPlaceholderText(_translate("MainWindow", "-3.5", None))
        self.ba1_quad7_strength_label.setText(_translate("MainWindow", "QUAD7 Strength in Dipole (k)", None))
        self.ba1_quad7_strength.setPlaceholderText(_translate("MainWindow", "2.5", None))
        self.s02_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.s02_quad1_strength.setPlaceholderText(_translate("MainWindow", "3.012", None))
        self.s02_quad2_strength.setPlaceholderText(_translate("MainWindow", "-4.719", None))
        self.s02_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.s02_quad3_strength.setPlaceholderText(_translate("MainWindow", "-4.07", None))
        self.s02_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.s02_quad4_strength.setPlaceholderText(_translate("MainWindow", "13.316", None))
        self.s02_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.vela_label.setText(_translate("MainWindow", "VELA", None))
        self.parameter_scan_to_value_label.setText(_translate("MainWindow", "Scan To:", None))
        self.parameter_scan_label.setText(_translate("MainWindow", "Parameter:", None))
        self.parameter_scan_step_size_label.setText(_translate("MainWindow", "Step Size:", None))
        self.parameter_scan_from_value_label.setText(_translate("MainWindow", "Scan From:", None))
        self.parameter_scan_section_label.setText(_translate("MainWindow", "Scan Parameters", None))
        self.directory_label.setText(_translate("MainWindow", "Directory", None))
        self.runButton.setText(_translate("MainWindow", "Run ASTRA", None))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.scan_tab), _translate("MainWindow", "Scan", None))
        self.directory_post_label.setText(_translate("MainWindow", "Directory 1", None))
        self.options_post_runs_label.setText(_translate("MainWindow", "Runs", None))
        self.options_post_plot_label.setText(_translate("MainWindow", "Beam Dynamic Plots", None))
        self.runButton_post.setText(_translate("MainWindow", "Start Post-processing", None))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.post_tab), _translate("MainWindow", "Post-Processing", None))
        self.directory_dyn_plot_label.setText(_translate("MainWindow", "Run directory", None))
        self.variables_dyn_plot_label.setText(_translate("MainWindow", "Variables to plot", None))
        self.runButton_dyn_plot.setText(_translate("MainWindow", "Generate plot", None))
        self.import_dist_dyn_plot_label.setText(_translate("MainWindow", "Import Distribution", None))
        self.save_plot_dyn_plot_label.setText(_translate("MainWindow", "Save Plot", None))
        self.output_file_dyn_plot_label.setText(_translate("MainWindow", "Output file", None))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.distribution_tab), _translate("MainWindow", "Distribution Plots", None))
        self.summary_title_label.setText(_translate("MainWindow", "Summary Plot", None))
        self.summary_save_plot_label.setText(_translate("MainWindow", "Save Plot", None))
        self.summary_output_file_label.setText(_translate("MainWindow", "Output file", None))
        self.runButton_summary.setText(_translate("MainWindow", "Generate plot", None))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.summary_tab), _translate("MainWindow", "Scan Summary", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionImport_YAML.setText(_translate("MainWindow", "Import YAML", None))
        self.actionExport_YAML.setText(_translate("MainWindow", "Export YAML", None))

from pyqtgraph import PlotWidget